### PR TITLE
Send welcome email when enabled

### LINKED ISSUE #302: registration with admin approval don't send welcome email after a user authorization
### Steps to reproduce
1.user request registration
2.create account
3.admin authorize user

### Expected behaviour
After admin authorization send the welcome email to the user

### Actual behaviour
No email are send after user authorization. I must select "resend welcome email"

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - customproperties: 1.0.1
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.1
  - login_notes: 0.4.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - occweb: 0.0.7
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - registration: 1.2.1
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - richdocuments
  - spreed
  - survey_client
  - user_ldap
  - user_status
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.gnosiagi.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/www.gnosiagi.org\/nc",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "occweb"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #302

### CODE REVIEW

File: lib/Listener/UserEnabledListener.php [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+		if ($event->getFeature() !== 'enabled') {
+			// Unrelated
+			return;
+		}
+
+		$user = $event->getUser();
+		$value = $this->config->getUserValue($user->getUID(), Application::APP_ID, 'send_welcome_mail_on_enable', 'no');
+		if ($value === 'yes') {
+			$this->config->deleteUserValue($user->getUID(), Application::APP_ID, 'send_welcome_mail_on_enable');
```
Comment (vitormattos) [inline lib/Listener/UserEnabledListener.php:59]: Idea: move this to `sendWelcomeMail` method

**Review by vitormattos — CHANGES_REQUESTED** [review]

File: lib/Listener/UserEnabledListener.php (hunk 1 above)
Comment (nickvergessen) [reply lib/Listener/UserEnabledListener.php:59]: Shouldn't have any impact, as when the user is enabled directly, the config is never set. But sure fine by me
